# Basic site settings
locale                   : "en-GB"
site_theme               : "default"
title                    : "Dr. Alexander Max Bauer"
title_separator          : "-"
name                     : &name "Dr. Alexander Max Bauer"
description              : &description "Philosopher • Scholar • Scientist"
url                      : https://alephmembeth.github.io
baseurl                  : ""
repository               : "https://github.com/alephmembeth/alephmembeth.github.io"

# Sidebar
author:
   # Biographic information
   avatar                : "amb_liri_runa.png"
   name                  : "Dr. Alexander Max Bauer"
   pronouns              :
   bio                   : "Philosopher • Scholar • Scientist"
   location              : "Oldenburg, Germany"
   employer              : "University of Oldenburg"
   uri                   :
   email                 : "alexander.max.bauer@uol.de"

   # Academic websites
   academia              : "https://uni-oldenburg.academia.edu/alexandermaxbauer"
   arxiv                 :
   googlescholar         : "https://scholar.google.de/citations?user=EFeokZUAAAAJ"
   inspire-hep           :
   impactstory           :
   orcid                 : "https://orcid.org/0000-0003-0923-6864"
   semantic              :
   pubmed                :
   researchgate          : "https://www.researchgate.net/profile/Alexander-Bauer-2"
   scopus                : "https://www.scopus.com/authid/detail.uri?authorId=57221999493"

   # Repositories and software development
   bitbucket             :
   codepen               :
   dribbble              :
   github                : "alephmembeth"
   kaggle                :
   stackoverflow         :

   # Social media
   artstation            :
   bluesky               :
   facebook              :
   flickr                :
   foursquare            :
   goodreads             :
   google_plus           :
   keybase               :
   instagram             :
   lastfm                :
   LinkedIn              : "alexandermaxbauer"
   mastodon              : "https://ohai.social/@alephmembeth"
   medium                :
   pinterest             :
   soundcloud            :
   steam                 :
   telegram              :
   tumblr                :
   twitter               : "alephmembeth"
   vine                  :
   weibo                 :
   wikipedia             : "Alephmembeth"
   xing                  : "AlexanderMax_Bauer"
   youtube               :
   zhihu                 :

# Publication categories
publication_category:
   books:
      title: 'Books'
   manuscripts:
      title: 'Journal Articles'
   conferences:
      title: 'Conference Papers'

# Site settings
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
   provider              :
   disqus:
      shortname          :
   discourse:
      server             :
   facebook:
      appid              :
      num_posts          :
      colorscheme        :
staticman:
   allowedFields         : ['name', 'email', 'url', 'message']
   branch                : "gh-pages"
   commitMessage         : "New comment."
   filename              : comment-{@timestamp}
   format                : "yml"
   moderation            : true
   path                  : "_data/comments/{options.slug}"
   requiredFields        : ['name', 'email', 'message']
   transforms:
      email              : "md5"
   generatedFields:
      date:
         type            : "date"
      options:
         format          : "iso8601"
atom_feed:
   hide                  : true
   path                  :

# SEO related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social sharing
twitter:
   username              : &twitter
facebook:
   username              :
   app_id                :
   publisher             :
og_image                 :
og_description           :
social:
   type                  :
   name                  :
   links                 :

# Analytics
analytics:
   provider              : "false"
   google:
      tracking_id        :

# Reading files
include:
   - .htaccess
   - _pages
   - files
exclude:
   - "*.sublime-project"
   - "*.sublime-workspace"
   - .asset-cache
   - .bundle
   - .github
   - .jekyll-assets-cache
   - .sass-cache
   - assets/js/_main.js
   - assets/js/plugins
   - assets/js/vendor
   - CHANGELOG
   - Capfile
   - config
   - Dockerfile
   - Gemfile
   - Gruntfile.js
   - gulpfile.js
   - license
   - local
   - log
   - node_modules
   - package.json*
   - Rakefile
   - README
   - tmp
   - vendor
keep_files:
   - .git
   - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown processing
kramdown:
   input: GFM
   hard_wrap: false
   auto_ids: true
   footnote_nr: 1
   entity_output: as_char
   toc_levels: 1..6
   smart_quotes: lsquo,rsquo,ldquo,rdquo
   enable_coderay: false

# Collections
collections:
   teaching:
      output: true
      permalink: /:collection/:path/
   publications:
      output: true
      permalink: /:collection/:path/
   portfolio:
      output: true
      permalink: /:collection/:path/
   talks:
      output: true
      permalink: /:collection/:path/


# Inclusion of pages and collections
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass
sass:
   sass_dir: _sass
   style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins
plugins:
   - jekyll-feed
   - jekyll-gist
   - jekyll-paginate
   - jekyll-sitemap
   - jekyll-redirect-from
   - jemoji

# Mimic GitHub Pages with --safe
whitelist:
   - jekyll-feed
   - jekyll-gist
   - jekyll-paginate
   - jekyll-sitemap
   - jekyll-redirect-from
   - jemoji


# Archives
category_archive:
   type: liquid
   path: /categories/
tag_archive:
   type: liquid
   path: /tags/

# HTML compression
compress_html:
   clippings: all
   ignore:
      envs: development
