title: Dr. Alexander Max Bauer
logo: /assets/img/amb_liri_runa.png
description: Philosopher • Scholar • Scientist
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
   - jekyll-remote-theme
defaults:
   -
      scope:
         path: ""
      values:
         custom_css: "/assets/css/custom.css"
